### ISSUE TITLE
Fix composer php dependency

### ISSUE THREAD

**Issue by soufiene-slimi** [tobiasdierich/gauge#2]
Laravel v6 require php >= 7.2.5
Laravel v7 require php >= 7.2.5
Laravel v8 require php >= 7.3

**composer.json**:
```javascript
"php": "^7.4",
"laravel/framework": "^6.0|^7.0|^8.0",
```

**Comment by tobiasdierich** [comment]
Hi, I've just downgraded the required php version to 7.2 and tagged a new release.
