### ISSUE TITLE
css & js is not in correct location

### ISSUE THREAD

**Issue by abbasmashaddy72** [tobiasdierich/gauge#7]
base.css is available in vendor/tobiasdierich/guage/public/base.css but in defult blade it is written as vendor/gauge/
AWA charts.js is availble in vendor/tobiasdierich/guage/public/charts.js but in defult blade it is written as vendor/gauge/

**Comment by tobiasdierich** [comment]
Did you run the `artisan gauge:install` command? If this does not work, can you trying to manually publish the gauge assets using the `artisan vendor:publish --tag gauge-assets --force` command?

**Comment by abbasmashaddy72** [comment]
I had manually added the location in defauld.blade.php it worked fine.

I will check the above lines you asked to perform.

**Comment by abbasmashaddy72** [comment]
No Change


![image](https://user-images.githubusercontent.com/55267488/110737655-c8576800-8253-11eb-9ea6-1f1c58370f37.png)

**Comment by tobiasdierich** [comment]
I can't reproduce your issue locally. Can you provide more details, such as the laravel version you are running. Can you also check if the issue persists if you install gauge in a fresh app?
